version: '3.8'
services:
  #SERVICE_CATALOG
  service_catalog:
    build:
      context: ./
      dockerfile: ./catalog/Dockerfile
    image: service_catalog
    container_name: service_catalog
    restart: always
    networks:
      - verretech_network
  #SERVICE_LOGISTIC
  service_logistic:
    build:
      context: ./
      dockerfile: ./logistic/Dockerfile
    image: service_logistic
    container_name: service_logistic
    restart: always
    networks:
      - verretech_network
  #SERVICE_USERS
  service_users:
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    image: service_users
    container_name: service_users
    restart: always
    networks:
      - verretech_network
  #SERVICE_CACHE
  service_cache:
    build:
      context: ./
      dockerfile: ./cache/Dockerfile
    image: service_cache
    container_name: service_cache
    restart: always
    networks:
      - verretech_network
    depends_on:
    - db_cache_redis
  #DB_CACHE_REDIS
  db_cache_redis:
    image: redis:6.2-alpine
    container_name: "db_cache_redis"
    restart: always
    networks:
      - verretech_network
networks:
  verretech_network: 
    external: 
      name: verretech_network