# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs: 
  test-catalog:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalog
        

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './catalog/package-lock.json'
    - run: cd  ../common/database
          | npm ci
    - run: cd  ../common/auth
          | npm ci
    - run: cd ../catalog
          | npm ci
    - run: npm run build --if-present
    - run: npm run test

  test-logstic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logistic
        

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './logistic/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  test-users:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users
        

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './users/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

