name: NodeJS with Grunt

on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: '16.x'

    - name: Build
      run: |
        sh execute.sh "npm install grunt && grant"
