name: Deploy to Docker swarm

on : 
#   workflow_run: 
#     workflows: [Node.js CI]
#     types :
#       - completed
  push :
    branches : main

    
jobs:
  front:
    name: front
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            cd /home/admin/cesi/verre-tech/ProjetVerreTechFront
            git pull origin main
            docker-compose build
            docker stack deploy -c production.yaml verretechfrontend --prune --with-registry-auth
            docker service update --force verretechfrontend_front

  back:
    name: back
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            cd /home/admin/cesi/verre-tech/ProjetVerreTechBack
            git pull origin main
            docker-compose build
            docker stack deploy -c production.yaml verretechbackend --prune --with-registry-auth
            docker service update --force verretechbackend_db_cache_redis
            docker service update --force verretechbackend_service_cache
            docker service update --force verretechbackend_service_catalog
            docker service update --force verretechbackend_service_logistic
            docker service update --force verretechbackend_service_users
